# frontend/traducoes.py

TRADUCOES = {
    "pt": {
        # Geral
        "app_title": "Plataforma de Gestão de Documentos",
        "login": "Login",
        "username": "Utilizador",
        "password": "Palavra-passe",
        "enter": "Entrar",
        "logout": "Sair",
        "back": "Voltar",
        "save": "Guardar",
        "cancel": "Cancelar",
        "close": "Fechar",
        "loading": "A carregar...",
        "no_data": "Sem dados",
        "error": "Erro",
        "success": "Sucesso",
        "select": "Selecione...",
        "select_document": "Selecione um documento...",
        "select_user": "Selecione um utilizador...",
        "select_option": "Escolha uma destas opções",
        
        # Perfis
        "parceiro": "Parceiro",
        "empresa": "Empresa",
        "admin": "Administrador",
        
        # Menu
        "menu_documents": "Meus Documentos",
        "menu_create": "Criar Documento",
        "menu_users": "Utilizadores",
        "menu_docs_company": "Documentos (empresa)",
        "menu_dashboard": "Dashboard",
        "menu_notifications": "Notificações",
        
        # Estados
        "estado_rascunho": "Rascunho",
        "estado_submetido": "Submetido",
        "estado_em_revisao": "Em Revisão",
        "estado_alteracoes": "Alterações",
        "estado_aprovado": "Aprovado",
        "estado_arquivado": "Arquivado",
        
        # Documentos
        "documents_title": "Documentos",
        "documents_summary": "Resumo de documentos",
        "new_document": "Novo Documento LCA/LCC",
        "document_title": "Título do documento",
        "document_state": "Estado",
        "document_version": "Versão",
        "document_last_update": "Última Atualização",
        "document_partner": "Parceiro",
        "document_id": "ID",
        "document_created": "Criado em",
        "no_documents": "Nenhum documento encontrado.",
        "create_first": "Comece por criar um novo documento.",
        "edit_document": "Editar documento",
        "view_data": "Ver dados em tabelas",
        "view_json": "Ver JSON bruto",
        "history": "Histórico de versões",
        "no_history": "Sem histórico disponível.",
        "export_excel": "Exportar Histórico",
        
        # Ações
        "action_submit": "Submeter",
        "action_approve": "Aprovar",
        "action_review": "Iniciar revisão",
        "action_request_changes": "Pedir alterações",
        "action_edit_again": "Editar novamente",
        "action_reopen": "Reabrir",
        "action_archive": "Arquivar",
        "action_archive_draft": "Arquivar (rascunho)",
        "action_close": "Fechar detalhes",
        "action_refresh": "Atualizar lista",
        "action_load": "Carregar documento",
        "action_create": "Criar documento",
        "action_save": "Guardar",
        
        # Notificações
        "notifications_title": "Notificações",
        "notifications_unread": "notificação não lida",
        "notifications_unread_plural": "notificações não lidas",
        "notifications_all_read": "Todas as notificações estão lidas.",
        "notifications_no": "Nenhuma notificação encontrada.",
        "notifications_mark_all_read": "Marcar todas como lidas",
        "notifications_mark_read": "Marcar lida",
        "notifications_read": "Lida",
        "notifications_view_doc": "Ver Documento",
        
        # Dashboard
        "dashboard_title": "Dashboard",
        "kpi_total": "Total Documentos",
        "kpi_approved": "Aprovados",
        "kpi_approval_rate": "Taxa Aprovação",
        "kpi_avg_review": "Tempo Médio Revisão",
        "kpi_days": "dias",
        "chart_distribution": "Distribuição de Documentos por Estado",
        "chart_bar": "Documentos por Estado (Barras)",
        "recent_docs": "Documentos Recentes",
        "top_partners": "Top Parceiros",
        "top_partners_title": "Parceiros com Mais Documentos",
        
        # Admin
        "admin_panel": "Painel Administrativo",
        "admin_users": "Gestão de Utilizadores",
        "admin_load_users": "Carregar utilizadores",
        "admin_new_user": "Novo Utilizador",
        "admin_manage_user": "Gerir Utilizador",
        "admin_change_password": "Alterar Password",
        "admin_new_password": "Nova password",
        "admin_change_pw_btn": "Alterar password",
        "admin_delete_user": "Eliminar utilizador",
        "admin_confirm_delete": "Confirmar eliminação",
        "admin_create_user": "Criar Novo Utilizador",
        "admin_full_name": "Nome Completo",
        "admin_profile": "Perfil",
        "admin_create_btn": "Criar Utilizador",
        "admin_user_created": "Utilizador criado com sucesso!",
        "admin_user_deleted": "Utilizador eliminado com sucesso!",
        "admin_pw_changed": "Password alterada com sucesso!",
        
        # Registro
        "register": "Registar",
        "register_title": "Criar Nova Conta",
        "register_username": "Utilizador",
        "register_password": "Palavra-passe",
        "register_full_name": "Nome Completo",
        "register_profile": "Perfil",
        "register_language": "Idioma / Language",
        "register_language_pt": "Português",
        "register_language_en": "English",
        "register_btn": "Criar Conta",
        "register_success": "Conta criada com sucesso!",
        "register_error": "Erro ao criar conta",
        "register_username_exists": "Utilizador já existe",
        "register_password_min": "A palavra-passe deve ter pelo menos 3 caracteres",
        "register_required": "Campo obrigatório",
        "register_have_account": "Já tem conta? Faça login",
        
        # Filtros
        "filters_title": "Filtros de Pesquisa",
        "filters_search": "Pesquisar",
        "filters_search_placeholder": "Título, parceiro ou ID...",
        "filters_state": "Estado",
        "filters_date_start": "Data Início",
        "filters_date_end": "Data Fim",
        "filters_order_by": "Ordenar por",
        "filters_order_direction": "Direção",
        "filters_order_asc": "Crescente",
        "filters_order_desc": "Decrescente",
        "filters_apply": "Aplicar Filtros",
        "filters_clear": "Limpar Filtros",
        
        # Mensagens de erro/sucesso
        "msg_credentials_invalid": "Credenciais inválidas",
        "msg_login_success": "Login efetuado com sucesso!",
        "msg_doc_created": "Documento criado com sucesso!",
        "msg_doc_updated": "Documento atualizado com sucesso!",
        "msg_doc_submitted": "Documento submetido com sucesso!",
        "msg_doc_approved": "Documento aprovado com sucesso!",
        "msg_doc_archived": "Documento arquivado com sucesso!",
        "msg_doc_reopened": "Documento reaberto com sucesso!",
        "msg_review_started": "Revisão iniciada com sucesso!",
        "msg_changes_requested": "Alterações solicitadas com sucesso!",
        "msg_doc_editable": "Documento reaberto para edição!",
        "msg_access_denied": "Acesso negado",
        "msg_not_found": "Não encontrado",
        "msg_comment_required": "É necessário um comentário para pedir alterações",
        "msg_password_min": "A password deve ter pelo menos 3 caracteres",
        "msg_self_delete": "Não pode eliminar a si próprio",
        "msg_export_error": "Erro ao exportar",
        
        # Outros
        "logged_as": "Logado como:",
        "notifications": "Notificações",
        "comment": "Comentário",
        "comment_placeholder": "Escreva um comentário...",
        "comment_required": "Comentário obrigatório",
    },
    "en": {
        # General
        "app_title": "Document Management Platform",
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "enter": "Login",
        "logout": "Logout",
        "back": "Back",
        "save": "Save",
        "cancel": "Cancel",
        "close": "Close",
        "loading": "Loading...",
        "no_data": "No data",
        "error": "Error",
        "success": "Success",
        "select": "Select...",
        "select_document": "Select a document...",
        "select_user": "Select a user...",
        "select_option": "Choose one of these options",
        
        # Profiles
        "parceiro": "Partner",
        "empresa": "Company",
        "admin": "Administrator",
        
        # Menu
        "menu_documents": "My Documents",
        "menu_create": "Create Document",
        "menu_users": "Users",
        "menu_docs_company": "Documents (company)",
        "menu_dashboard": "Dashboard",
        "menu_notifications": "Notifications",
        
        # States
        "estado_rascunho": "Draft",
        "estado_submetido": "Submitted",
        "estado_em_revisao": "Under Review",
        "estado_alteracoes": "Changes Requested",
        "estado_aprovado": "Approved",
        "estado_arquivado": "Archived",
        
        # Documents
        "documents_title": "Documents",
        "documents_summary": "Document Summary",
        "new_document": "New LCA/LCC Document",
        "document_title": "Document Title",
        "document_state": "Status",
        "document_version": "Version",
        "document_last_update": "Last Update",
        "document_partner": "Partner",
        "document_id": "ID",
        "document_created": "Created At",
        "no_documents": "No documents found.",
        "create_first": "Start by creating a new document.",
        "edit_document": "Edit Document",
        "view_data": "View data in tables",
        "view_json": "View raw JSON",
        "history": "Version History",
        "no_history": "No history available.",
        "export_excel": "Export History",
        
        # Actions
        "action_submit": "Submit",
        "action_approve": "Approve",
        "action_review": "Start Review",
        "action_request_changes": "Request Changes",
        "action_edit_again": "Edit Again",
        "action_reopen": "Reopen",
        "action_archive": "Archive",
        "action_archive_draft": "Archive (draft)",
        "action_close": "Close Details",
        "action_refresh": "Refresh List",
        "action_load": "Load Document",
        "action_create": "Create Document",
        "action_save": "Save",
        
        # Notifications
        "notifications_title": "Notifications",
        "notifications_unread": "unread notification",
        "notifications_unread_plural": "unread notifications",
        "notifications_all_read": "All notifications are read.",
        "notifications_no": "No notifications found.",
        "notifications_mark_all_read": "Mark all as read",
        "notifications_mark_read": "Mark as read",
        "notifications_read": "Read",
        "notifications_view_doc": "View Document",
        
        # Dashboard
        "dashboard_title": "Dashboard",
        "kpi_total": "Total Documents",
        "kpi_approved": "Approved",
        "kpi_approval_rate": "Approval Rate",
        "kpi_avg_review": "Avg Review Time",
        "kpi_days": "days",
        "chart_distribution": "Document Distribution by Status",
        "chart_bar": "Documents by Status (Bar)",
        "recent_docs": "Recent Documents",
        "top_partners": "Top Partners",
        "top_partners_title": "Partners with Most Documents",
        
        # Admin
        "admin_panel": "Administrative Panel",
        "admin_users": "User Management",
        "admin_load_users": "Load Users",
        "admin_new_user": "New User",
        "admin_manage_user": "Manage User",
        "admin_change_password": "Change Password",
        "admin_new_password": "New password",
        "admin_change_pw_btn": "Change password",
        "admin_delete_user": "Delete user",
        "admin_confirm_delete": "Confirm deletion",
        "admin_create_user": "Create New User",
        "admin_full_name": "Full Name",
        "admin_profile": "Profile",
        "admin_create_btn": "Create User",
        "admin_user_created": "User created successfully!",
        "admin_user_deleted": "User deleted successfully!",
        "admin_pw_changed": "Password changed successfully!",
        
        # Register
        "register": "Register",
        "register_title": "Create New Account",
        "register_username": "Username",
        "register_password": "Password",
        "register_full_name": "Full Name",
        "register_profile": "Profile",
        "register_language": "Idioma / Language",
        "register_language_pt": "Português",
        "register_language_en": "English",
        "register_btn": "Create Account",
        "register_success": "Account created successfully!",
        "register_error": "Error creating account",
        "register_username_exists": "Username already exists",
        "register_password_min": "Password must be at least 3 characters",
        "register_required": "Required field",
        "register_have_account": "Already have an account? Login",
        
        # Filters
        "filters_title": "Search Filters",
        "filters_search": "Search",
        "filters_search_placeholder": "Title, partner or ID...",
        "filters_state": "Status",
        "filters_date_start": "Start Date",
        "filters_date_end": "End Date",
        "filters_order_by": "Order By",
        "filters_order_direction": "Direction",
        "filters_order_asc": "Ascending",
        "filters_order_desc": "Descending",
        "filters_apply": "Apply Filters",
        "filters_clear": "Clear Filters",
        
        # Messages
        "msg_credentials_invalid": "Invalid credentials",
        "msg_login_success": "Login successful!",
        "msg_doc_created": "Document created successfully!",
        "msg_doc_updated": "Document updated successfully!",
        "msg_doc_submitted": "Document submitted successfully!",
        "msg_doc_approved": "Document approved successfully!",
        "msg_doc_archived": "Document archived successfully!",
        "msg_doc_reopened": "Document reopened successfully!",
        "msg_review_started": "Review started successfully!",
        "msg_changes_requested": "Changes requested successfully!",
        "msg_doc_editable": "Document reopened for editing!",
        "msg_access_denied": "Access denied",
        "msg_not_found": "Not found",
        "msg_comment_required": "A comment is required to request changes",
        "msg_password_min": "Password must be at least 3 characters",
        "msg_self_delete": "You cannot delete yourself",
        "msg_export_error": "Export error",
        
        # Other
        "logged_as": "Logged as:",
        "notifications": "Notifications",
        "comment": "Comment",
        "comment_placeholder": "Write a comment...",
        "comment_required": "Comment required",
    }
}

def t(texto: str, idioma: str = "pt") -> str:
    """Retorna a tradução do texto para o idioma especificado."""
    if idioma not in TRADUCOES:
        idioma = "pt"
    return TRADUCOES[idioma].get(texto, texto)